#!/usr/bin/env bash
#PBS -N chapter6
#PBS -q classgpu
#PBS -l select=1:gpuname=ampere:ngpus=1:ncpus=1:mpiprocs=1:mem=8000mb
#PBS -l walltime=1:00:00
#PBS -j oe
#PBS -o example.qsub_out

# change into submission directory
cd $PBS_O_WORKDIR

export PATH=$PATH:/apps/x86-64/apps/cuda_12.6.0/bin

# list NVIDIA cards, make clean, load the cuda module, make, and run main
lspci -vvv | grep "NVIDIA" && \
  make clean && \
  make main && \
  ./main $INPUT_IMAGE $INPUT_META
